#!/usr/bin/env bash
#
n=1
while [ $n -lt 101 ];
do
	if [ $(( n % 5 )) == 0 ] && [ $(( n % 3 )) == 0 ]; then
	echo "FizzBuzz"
 elif [ $(( n % 5 )) == 0 ];
 then
	 echo "Buzz"
	    elif [ $(( n % 3 )) == 0 ];
	    then
	echo "Fizz"
	    else
    	echo $n
	fi
	n=$(( n + 1 ))	
done
