#!/usr/bin/env bash
#
n=1
while [ $n -lt 101 ]
do
	case $n in "$((n % 5)) == 0 ")
	      echo "FizzBuzz"

	       " $((n % 3 )) == 0 " 
	
		echo "FizzBuzz"

		 " $((n % 3 )) == 0 "

		echo "Fizz";;
		 " $((n % 5 )) == 0 ")
	echo "buzz";;
	
esac
	n=$(( n + 1))
done
