#!/usr/bin/env bash
#This script displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
z=1
while [ $z -lt 11 ]
do
	if [ $z -eq 9 ]
	then 
		echo -e "Best School\nHi"
	else 
		echo "Best School"
	fi 
	z=$(( z + 1))
done
