#!/usr/bin/env bash
#
for file in * 
do 
	if [ "$file" = school ]
	then 
		echo "school file exist"
	if [ -s "$file" ]
then 
	echo "school file is empty"
else 
	echo "school file is not empty"
		fi
if [ -f "$file" ]
then
	echo "school is a regular file" 
fi 
	fi

done
if [ "$file" ] 
then
	echo "school file does not exist"
fi
