#!/usr/bin/env bash
#
x=0
for file in * 
do 
	if [ "$file" = school ]
	then 
		x=$(( x + 1 ))
		echo "school file exist"
	if [ -s "$file" ]
then 
	echo "school file is not empty"
else 
	echo "school file is empty"
		fi
if [ -f "$file" ]
then
	echo "school is a regular file" 

fi
	fi
done
if [ $x -eq 0 ]
then
	                echo "school file does not exist"
fi
