#!/usr/bin/env bash
#
x=/var/run/myscript.pid
echo $$ >> $x
while [ $x -gt 0 ]
do
       echo "To infinity and beyond"
       sleep 2
done
trap -l 'echo I hate the kill command; sudo rm $x; exit' -15
trap -l 'echo Y U no love me?!' -2
trap -l 'sudo rm $x; exit' -3

