#!/usr/bin/env bash
#
x="myscript.pid"
echo $$ >> $x

trap 'echo I hate the kill command; sudo rm $x; exit' 15
trap 'echo Y U no love me?!' 2
trap 'sudo rm $x; exit' 3
while [ $x -gt 0 ]
do
	        echo "To infinity and beyond"
		        sleep 2
		done
