#!/usr/bin/env bash
#
File=/var/run/my_process.pid

if [ "$1" == "start" ];
then
      	./manage_my_process &
 echo $$ > $File
 echo "manage_my_process started"
 
elif [ "$1" == "stop" ];
then
	kill ./manage_my_process
	sudo rm $File
	echo "manage_my_process stopped"

 elif [ "$1" == "restart" ];
then
	   pkill -f ./manage_my_process
	   sudo rm $File
	   ./manage_my_process &
	   echo $$ > $File
	   echo "manage_my_process restarted"
 else
	   echo "Usage: manage_my_process {start|stop|restart}"

fi	   
