#!/usr/bin/env bash
#
file=/var/run/my_process.pid

if [ "$1" = "start" ];
then 
       ./manage_my_process & echo $$ > $file
    echo "manage_my_process started"

elif [ "$2" = "stop" ];
then
	 pkill -f ./manage_my_process
	 sudo rm $file
	 echo "manage_my_process stopped"

 elif [ "$3" = "restart" ];
then
	   pkill -f ./manage_my_process
	   sudo rm $file ./manage_my_process &
	   echo $$ > $file
	   echo "manage_my_process restarted"
 else
	   echo "Usage: manage_my_process {start|stop|restart}"

fi	   
